wandb_version: 1

epoch:
  desc: null
  value: 51
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700888002.117666
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.15.10
      8:
      - 3
      - 5
