wandb_version: 1

k:
  desc: null
  value: 21
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.10
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696355158.942496
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.15.10
      8:
      - 3
      - 5
